### ISSUE TITLE
"Hello, I have used your project to connect to my DayZ server. However, regardless of how I change the output method, I can only retrieve 1027 characters of data. When the content exceeds this length, it cannot be displayed. Please help me resolve this issue. Thank you."

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [conqp/rcon#17] opened 2023-07-24 10:46 UTC
![1](https://github.com/conqp/rcon/assets/81788251/8940d2a2-50ec-45f7-9931-4bfbf4b648f0)
plz

**Comment by conqp** [comment] 2023-07-24 12:36
Please test wether 5ed357208027899e57307a5df83ae3c8d81ae47b fixes this issue.

**Comment by conqp** [comment] 2023-07-24 14:41
1.  Please do not post pictures of code, but the actual code as text.
2.  As per the README, you need at least Python 3.10.

**Comment by yuanshangyujingshierlou** [comment] 2023-07-25 02:03
> 1. Please do not post pictures of code, but the actual code as text.
> 2. As per the README, you need at least Python 3.10.
> 3. Please try again, with Python 3.10 or higher, if release `2.4.0` fixes the issue.

Thank you for your help, but this issue has not been resolved
![1](https://github.com/conqp/rcon/assets/81788251/ae30a8e0-7165-4f53-a5a1-cac505fc34b0)

**Comment by yuanshangyujingshierlou** [comment] 2023-07-25 02:04
> 1. Please do not post pictures of code, but the actual code as text.
> 2. As per the README, you need at least Python 3.10.
> 3. Please try again, with Python 3.10 or higher, if release `2.4.0` fixes the issue.

Sorry, I have posted another image. This is the code
==============================================================================
from rcon.battleye import Client
from rcon.battleye.proto import ServerMessage

# # 删除数组中的所有空格
# def remove_all_space(list):
#     while '' in list:
#         list.remove('')
#     return list


def my_message_handler(server_message: ServerMessage) -> None:
    """Print server messages."""
    print(server_message.message)


player_list = []
with Client('49.70.0.103',22314,passwd='123zxc..',message_handler=my_message_handler) as client:
    response = client.run('players')
    print(response)
    print(response.__len__())

**Comment by yuanshangyujingshierlou** [comment] 2023-07-25 02:05
> 1. Please do not post pictures of code, but the actual code as text.
> 2. As per the README, you need at least Python 3.10.
> 3. Please try again, with Python 3.10 or higher, if release `2.4.0` fixes the issue.

Sorry, I have posted another image. This is the code
==================================================================================from rcon.battleye import Client
from rcon.battleye.proto import ServerMessage



def my_message_handler(server_message: ServerMessage) -> None:
    """Print server messages."""
    print(server_message.message)


player_list = []
with Client('ip',22314,passwd='123456',message_handler=my_message_handler) as client:
    response = client.run('players')
    print(response)
    print(response.__len__())

**Comment by conqp** [comment] 2023-07-25 09:24
Thank you for providing a reproducible example and thus access to a server with a sufficiently large response to reproduce the issue.

I was able to pinpoint the problem, which is command response fragementation, while the `seq` remains unchanged.

The issue is resolved in 6bd88282dbb2b6fb92cc48531861df73bc416c03 and the latest release of `2.4.2` which is available in the AUR and on PyPI.

For security reasons, you should now change the credentials (i.e. at least the password) to your RCon server.

**Closed by conqp** 2023-07-25 09:24 UTC

**Comment by yuanshangyujingshierlou** [comment] 2023-07-25 13:59
> 感谢您提供可重现的示例，从而访问具有足够大响应的服务器来重现该问题。
> 
> 我能够查明问题所在，即命令响应碎片，但`seq`保持不变。
> 
> 该问题已在[6bd8828](https://github.com/conqp/rcon/commit/6bd88282dbb2b6fb92cc48531861df73bc416c03)中得到解决，最新版本`2.4.2`可在 AUR 和 PyPI 中找到。
> 
> 出于安全原因，您现在应该更改 RCon 服务器的凭据（即至少是密码）。

Thank you again for your help, your project is excellent!!! I will change the server rcon password. Thank you
